### ISSUE TITLE
nonesense error at shader compilation

### ISSUE THREAD

**Issue by meutzitzu** [Kravantokh/OpenGL_GLEW_GLFW_template#2]
Sometimes the error handler does not properly print some errors in shader compilation.

`Uniform location: 1Error during shader compilation: 0(60) : error C0000: syntax error, unexpected $undefined at token "<undefined>"`

**Comment by Kravantokh** [comment]
First of all, the error is not exactly nonsense and it comes straight from OpenGL, not the library. The library just displays it. It most likely refers to a stray (invalid) character in the input.

I have met this bug myself several times, but have not managed to reproduce it reliably and thus could not fix it.
If a way to reliably reproduce it is found let me know and I will try my best to fix it.

Other than that, the only way to find its source is through guesswork, so if no way to reproduce it is found I shall rewrite the shader parser code. On Linux it should be rewritten either way with mmap, because that is more elegant than reading it character by character (I wasn't very inspired when I wrote that code).

On Windows I will be waiting for a pull request if the bug occurs, because I do not currently use windows and thus can not test it and there is no mmap on Windows that is identical to the one in Linux (as far as I know).

The issue remains open until a solution is found.

**Comment by Kravantokh** [comment]
Updated the file I/O code with mmap (on Linux). Now we shall see whether the issue persists. For me it has not reappeared yet, but that may be a fluke due to its random-like nature.

**Comment by meutzitzu** [comment]
After pulling the changes to file I/O and using it for about 3 days I have not gotten that error again so I think it's pretty safe to assume that's where the problem was and it has now been fixed
